  name: Iris Project CI/CD

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Set up python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Checkout repository
          uses: actions/checkout@v2
            
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install pandas scikit-learn
            pip install seaborn

        - name: Run Unit Tests
          run:  |
            python -m unittest discover -s . -p "*.py"

    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Deploy to environment
          run: |
            echo "Could deploy model somwhere if we wanted."
